### ISSUE TITLE
Share Recipe Via Email

### ISSUE THREAD

**Issue by sheetalmangate** [sheetalmangate/project2#6]
User Story : Include an option to send the recipe via email

Acceptance Criteria : 
-- Provide an option labeled "Share Recipe" . This option should be added to top of page. Once design is ready we can move it to appropriate place .
-- Selecting "Share Recipe" should open page with two fields
    1) Recipe
    2) Email id
-- After Submitting page recipient can get email with recipe

**Comment by jdeluna06** [comment]
In progress

**Comment by jdeluna06** [comment]
completed and approved
